import { Foo, Nav } from "@/components";
import "./globals.css";
import { Rutas } from "@/models";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="relative font-monse  bg-opacity-30">

        <Nav pathNames={[Rutas.HOME, Rutas.CATALOGO, Rutas.CONTACTO]} />

          <div className="pt-14 flex justify-center items-center">
            
            <div className="max-w-6xl min-h-screen z-40 w-full p-2">
              {children}
            </div>

          </div>
        
         <Foo />
      </body>
    </html>
  );
}
